apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: react-app
